from django.db import models

# Create your models here.
class Class(models.Model):
	ccn = models.TextField()
	header = models.TextField()
	deptName = models.TextField()
	deptCode = models.TextField()
	courseNumber = models.TextField()
	secNum = models.TextField()
	type = models.TextField()
	shortTitle = models.TextField()
	longTitle = models.TextField()
	location = models.TextField()
	schedule_raw = models.TextField()
	meetingDays = models.TextField()
	startHour = models.TextField()
	startMinutes = models.TextField()
	startPeriod = models.TextField()
	endHour = models.TextField()
	endMinutes = models.TextField()
	endPeriod = models.TextField()
	instructor = models.TextField()
	units = models.IntegerField(null=True, blank=True)
	note = models.TextField()
	finalExam_raw = models.TextField()
	description = models.TextField()
	enrollLimit = models.IntegerField()
	enrollEnrolled = models.IntegerField()
	enrollWaitlist = models.IntegerField()
	enrollAvailible = models.IntegerField()